// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdszqjxcsjnmwhdegpjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhkc3pxanhjc2pubXdoZGVncGpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MzE0MDAsImV4cCI6MjA2MjEwNzQwMH0.2BKoPpJNpTsV3e1uXjd8rNTw-s-3bKXD_OkVrPO-Qmk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);